### PR TITLE
The constant is constants.ok not constants.OK

### PR DESCRIPTION
**Pull request by baudehlo**

### CODE REVIEW

**Comment by msimerson** [comment]
Actually, as of [version 1.0.2](https://github.com/haraka/haraka-constants/commit/54878ec639ca118433da96c6d62f3b5a5b4fe77b) the constants are exported in lower (legacy) and uppercase formats. That matches what the docs imply and it's what we **SHOULD** be using, because programmers expect constants to be in all caps. The only change needed here is to require haraka-constants >= 1.0.2.

**Comment by baudehlo** [comment]
Ok happy to change the PR to do that.

**Comment by msimerson** [comment]
Awesome. Feel free to also bump the version number, update Changes.md and publish to NPM after the CI tests pass.

**Comment by baudehlo** [comment]
I dropped the ball on this one. Updated now.

**Comment by baudehlo** [comment]
Merged and published.

**Pull request merged**
